### ISSUE TITLE
RedHat Tech Ready Hands-On Labs issue report

### ISSUE THREAD

**Issue by SammZhu** [RHFieldProductManagement/baremetal-ipi-lab#3]
I was following the instruction docs and deploying the openShift cluster in the lab environment. I couldn't successfully finish the cluster installation step, I could make it on 26th Oct. , but I couldn't since yesterday. Here are logs:
----------------------------------------------------------------------------------
$HOME/scripts/openshift-baremetal-install --dir=ocp --log-level debug create cluster

E1027 22:34:38.135873   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:34:39.137168   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:34:40.138545   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:34:41.139890   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:34:42.141394   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:34:43.142984   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:34:44.144986   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:34:45.147222   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:34:46.149036   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:34:47.151252   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
......
......
......
E1027 22:52:00.253775   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:52:01.255590   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
E1027 22:52:02.257255   34891 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ClusterVersion: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&limit=500&resourceVersion=0: EOF
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://api.s7vw6.dynamic.opentlc.com:6443/apis/config.openshift.io/v1/clusteroperators: EOF
FATAL failed to initialize the cluster: Working towards 4.5.12: 82% complete, waiting on authentication, cluster-autoscaler, console, csi-snapshot-controller, ingress, kube-storage-version-migrator, machine-api, marketplace, monitoring, openshift-apiserver, openshift-samples, operator-lifecycle-manager-packageserver

**Comment by rdoxenham** [comment]
Resolved directly with reporter - was a filesystem corruption issue.
